version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use Python 3.8 environment
    steps:
      - checkout  # Check out your code from GitHub

      # Set up dependencies
      - run:
          name: Set up Python environment and install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            python -m unittest discover

workflows:
  version: 2
  test:
    jobs:
      - test
