version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install junit-xml
      - run:
          name: Run Tests
          command: |
            python3 -m unittest discover -v > test-results/output.txt
            python3 -m unittest discover -v | tee test-results/output.xml | junit2html test-results/output.xml test-results/test-report.html
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
