version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      
      # Create test-results directory
      - run:
          name: Create Test Results Directory
          command: mkdir -p test-results
      
      # Install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      
      # Run tests and generate XML output
      - run:
          name: Run Tests
          command: python -m xmlrunner TestTriangle.py --output test-results/results.xml
      
      # Store test results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  testing_triangles:
    jobs:
      - build-and-test
