version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8 # Choose your Python version
    steps:
      - checkout # Check out the code from the repository
      - run:
          name: Run Tests
          command: |
            python -m unittest discover -s test-results  # Adjust command as needed
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - build
