version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Automated Tests
          command: |
            pytest --junitxml=test-results/results.xml automated_tests/
      - run:
          name: Run Manual Tests
          command: |
            # Command to run your manual tests, if any
            # e.g., python manual_tests/run_manual_tests.py
      - store_test_results:
          path: test-results

workflows:
  version: 2
  testing_triangles:
    jobs:
      - build-and-test
