version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use Python 3.8 environment
    steps:
      - checkout  # Check out your code from GitHub

      # Set up dependencies
      - run:
         
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      #- run:
          name: Run Tests
          command: python -m xmlrunner TestTriangle.py --output test-results/results.xml
      
      # Store test results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
